#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get -y update
sudo apt-get install -y haproxy

server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 338717-web-01 54.236.53.170:80 check
        server 338717-web-02 34.201.164.75:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
