#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#!/usr/bin/env bash

i=1

while [ $i -le 10 ]; do
    if [ $i -eq 10 ]; then
        echo "Hi"
    fi
        echo "Best School"
    ((i++))
done

