#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes

hour=0
mins=1

while [ $hour -ne 13 ]; do
    echo "Hour: $hour"
    while [ $mins -ne 60 ]; do
        echo "$mins"
        ((mins++))
    done
    ((hour++))
    mins=0
done
