#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get install -y nginx
sudp sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i '/listen 80;/a listen 8080 default_server;' /etc/nginx/sites-available/default
sudo systemctl restart nginx